# Generated by Django 5.2.3 on 2025-06-12 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_campeonato', models.CharField(max_length=50, verbose_name='Nombre del campeonato')),
                ('nombre_auspiciante', models.CharField(max_length=50, verbose_name='Nombre del auspiciante')),
            ],
        ),
        migrations.CreateModel(
            name='EquipoFutbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del equipo')),
                ('siglas', models.CharField(max_length=10, verbose_name='Siglas')),
                ('username_twitter', models.CharField(max_length=30, verbose_name='Usuario de Twitter')),
            ],
        ),
        migrations.CreateModel(
            name='CampeonatoEquipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField(verbose_name='Año')),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='futbolec.campeonato')),
                ('equipo_futbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campeonatos', to='futbolec.equipofutbol')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del jugador')),
                ('posicion_campo', models.CharField(choices=[('arquero', 'Arquero'), ('defensa', 'Defensa'), ('mediocampo', 'Mediocampo'), ('delantero', 'Delantero')], max_length=20, verbose_name='Posición en el campo')),
                ('numero_camiseta', models.IntegerField(verbose_name='Número de camiseta')),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sueldo')),
                ('equipo_futbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='futbolec.equipofutbol')),
            ],
        ),
    ]
